// <auto-generated />
using System;
using Fusion.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fusion.Repository.Migrations
{
    [DbContext(typeof(FusionDbContext))]
    [Migration("20251015092212_AddLinkURLMobileAndWebInNotification")]
    partial class AddLinkURLMobileAndWebInNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fusion.Repository.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AvatarCompany")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_company");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("ImageCompany")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_company");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.CompanyFriendship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CompanyAId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_a_id");

                    b.Property<Guid?>("CompanyBId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_b_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("LastActionBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_action_by");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requester_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBId");

                    b.HasIndex("LastActionBy");

                    b.HasIndex(new[] { "CompanyAId", "CompanyBId" }, "UX_Friendships_Pair_Active")
                        .IsUnique()
                        .HasFilter("([status] IN ('pending', 'accepted'))");

                    b.ToTable("CompanyFriendships");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.CompanyMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CompanyId", "UserId" }, "UX_CompanyMembers_Unique")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [user_id] IS NOT NULL)");

                    b.ToTable("CompanyMembers");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.FunctionInPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FunctionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("function_code");

                    b.Property<string>("FunctionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("function_name");

                    b.Property<string>("PageCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("page_code");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("FunctionInPages");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Event")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("LinkUrlMobile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link_url_mobile");

                    b.Property<string>("LinkUrlWeb")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("link_url_web");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CreateAt" }, "IX_Notifications_User_Time")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_User_Unread")
                        .HasFilter("([is_read]=(0))");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CompanyHiredId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_hired_id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsHired")
                        .HasColumnType("bit")
                        .HasColumnName("isHired");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_request_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyHiredId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorkflowId");

                    b.HasIndex(new[] { "ProjectRequestId" }, "UQ__Projects__B79D8DD66555382B")
                        .IsUnique()
                        .HasFilter("[project_request_id] IS NOT NULL");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPartner")
                        .HasColumnType("bit")
                        .HasColumnName("isPartner");

                    b.Property<bool>("IsViewAll")
                        .HasColumnType("bit")
                        .HasColumnName("isViewAll");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ProjectId", "UserId" }, "UX_ProjectMembers_Unique")
                        .IsUnique()
                        .HasFilter("([project_id] IS NOT NULL AND [user_id] IS NOT NULL)");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ConvertedProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("converted_project_id");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("ExecutorCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executor_company_id");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RequesterCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requester_company_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExecutorCompanyId");

                    b.HasIndex("RequesterCompanyId");

                    b.HasIndex(new[] { "ConvertedProjectId" }, "UQ__ProjectR__FDFB014B54F36625")
                        .IsUnique()
                        .HasFilter("[converted_project_id] IS NOT NULL");

                    b.ToTable("ProjectRequests");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("due_date");

                    b.Property<string>("Img")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("img");

                    b.Property<bool>("IsBacklog")
                        .HasColumnType("bit")
                        .HasColumnName("is_backlog");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("OrderInSprint")
                        .HasColumnType("int")
                        .HasColumnName("order_in_sprint");

                    b.Property<int?>("Point")
                        .HasColumnType("int")
                        .HasColumnName("point");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SprintId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId", "RoleName" }, "UX_Roles_Company_RoleName")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [role_name] IS NOT NULL)");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("int")
                        .HasColumnName("function_id");

                    b.Property<bool>("IsAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_access");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "CompanyId", "RoleId", "FunctionId" }, "UX_RolePermissions_Unique")
                        .IsUnique()
                        .HasFilter("([company_id] IS NOT NULL AND [role_id] IS NOT NULL AND [function_id] IS NOT NULL)");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.SubscriptionPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("QuotaCompany")
                        .HasColumnType("int")
                        .HasColumnName("quota_company");

                    b.Property<int>("QuotaProject")
                        .HasColumnType("int")
                        .HasColumnName("quota_project");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPackages");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TaskLogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_id");

                    b.Property<string>("ChangedCols")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("changed_cols");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("NewRow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_row");

                    b.Property<string>("OldRow")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_row");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskLogEvent");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TaskWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AssignUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assign_user_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("task_id");

                    b.Property<Guid?>("WorkflowStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_status_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("WorkflowStatusId");

                    b.ToTable("TaskWorkflow");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("budget");

                    b.Property<DateTime?>("ClosedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit")
                        .HasColumnName("is_billable");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsHighestUrgen")
                        .HasColumnType("bit")
                        .HasColumnName("is_highest_urgen");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submitted_by");

                    b.Property<string>("TicketName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ticket_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Urgency")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("urgency");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TicketComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Visibility")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TransactionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("package_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionPayments");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("google_sub");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_system_admin");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(128)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("userName");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GoogleSub" }, "UQ__Users__74328F6E0433F7F6")
                        .IsUnique()
                        .HasFilter("[google_sub] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email_NotNull")
                        .IsUnique()
                        .HasFilter("([email] IS NOT NULL)");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("create_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("device_token");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("platform");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "UX_UserRoles_Unique")
                        .IsUnique()
                        .HasFilter("([user_id] IS NOT NULL AND [role_id] IS NOT NULL)");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int>("QuotaCompanyAdded")
                        .HasColumnType("int")
                        .HasColumnName("quota_company_added");

                    b.Property<int>("QuotaCompanyRemaining")
                        .HasColumnType("int")
                        .HasColumnName("quota_company_remaining");

                    b.Property<int>("QuotaProjectAdded")
                        .HasColumnType("int")
                        .HasColumnName("quota_project_added");

                    b.Property<int>("QuotaProjectRemaining")
                        .HasColumnType("int")
                        .HasColumnName("quota_project_remaining");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.WorkflowStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GuardNameKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("guard_name_key");

                    b.Property<bool>("IsEnd")
                        .HasColumnType("bit")
                        .HasColumnName("is_end");

                    b.Property<bool>("IsStart")
                        .HasColumnType("bit")
                        .HasColumnName("is_start");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WorkflowId", "Name" }, "UX_WorkflowStatus_Name")
                        .IsUnique()
                        .HasFilter("([workflow_id] IS NOT NULL AND [name] IS NOT NULL)");

                    b.ToTable("WorkflowStatus");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.WorkflowTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_status_id");

                    b.Property<Guid?>("ToStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("to_status_id");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex(new[] { "WorkflowId", "FromStatusId", "ToStatusId" }, "UX_WorkflowTransitions_Unique")
                        .IsUnique()
                        .HasFilter("([workflow_id] IS NOT NULL AND [from_status_id] IS NOT NULL AND [to_status_id] IS NOT NULL)");

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Comment", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "AuthorUser")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("FK_Comments_Author");

                    b.HasOne("Fusion.Repository.Entities.ProjectTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_Comments_Task");

                    b.Navigation("AuthorUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Company", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "OwnerUser")
                        .WithMany("Companies")
                        .HasForeignKey("OwnerUserId")
                        .HasConstraintName("FK_Companies_OwnerUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.CompanyFriendship", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "CompanyA")
                        .WithMany("CompanyFriendshipCompanyAs")
                        .HasForeignKey("CompanyAId")
                        .HasConstraintName("FK_CompanyFriendships_A");

                    b.HasOne("Fusion.Repository.Entities.Company", "CompanyB")
                        .WithMany("CompanyFriendshipCompanyBs")
                        .HasForeignKey("CompanyBId")
                        .HasConstraintName("FK_CompanyFriendships_B");

                    b.HasOne("Fusion.Repository.Entities.User", "LastActionByNavigation")
                        .WithMany("CompanyFriendships")
                        .HasForeignKey("LastActionBy")
                        .HasConstraintName("FK_CompanyFriendships_LastActor");

                    b.Navigation("CompanyA");

                    b.Navigation("CompanyB");

                    b.Navigation("LastActionByNavigation");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.CompanyMember", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "Company")
                        .WithMany("CompanyMembers")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_CompanyMembers_Company");

                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("CompanyMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CompanyMembers_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Notification", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Project", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "CompanyHired")
                        .WithMany("ProjectCompanyHireds")
                        .HasForeignKey("CompanyHiredId")
                        .HasConstraintName("FK_Projects_HiredCompany");

                    b.HasOne("Fusion.Repository.Entities.Company", "Company")
                        .WithMany("ProjectCompanies")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Projects_Company");

                    b.HasOne("Fusion.Repository.Entities.User", "CreatedByNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Projects_CreatedBy");

                    b.HasOne("Fusion.Repository.Entities.ProjectRequest", "ProjectRequest")
                        .WithOne("Project")
                        .HasForeignKey("Fusion.Repository.Entities.Project", "ProjectRequestId")
                        .HasConstraintName("FK_Projects_Request");

                    b.HasOne("Fusion.Repository.Entities.Workflow", "Workflow")
                        .WithMany("Projects")
                        .HasForeignKey("WorkflowId")
                        .HasConstraintName("FK_Projects_Workflow");

                    b.Navigation("Company");

                    b.Navigation("CompanyHired");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ProjectRequest");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectMember", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_ProjectMembers_Project");

                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ProjectMembers_User");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectRequest", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "CreatedByNavigation")
                        .WithMany("ProjectRequests")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_PRQ_CreatedBy");

                    b.HasOne("Fusion.Repository.Entities.Company", "ExecutorCompany")
                        .WithMany("ProjectRequestExecutorCompanies")
                        .HasForeignKey("ExecutorCompanyId")
                        .HasConstraintName("FK_PRQ_Executor");

                    b.HasOne("Fusion.Repository.Entities.Company", "RequesterCompany")
                        .WithMany("ProjectRequestRequesterCompanies")
                        .HasForeignKey("RequesterCompanyId")
                        .HasConstraintName("FK_PRQ_Requester");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ExecutorCompany");

                    b.Navigation("RequesterCompany");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectTask", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "CreatedByNavigation")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_ProjectTasks_CreatedBy");

                    b.HasOne("Fusion.Repository.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_ProjectTasks_Project");

                    b.HasOne("Fusion.Repository.Entities.Sprint", "Sprint")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("SprintId")
                        .HasConstraintName("FK_ProjectTasks_Sprint");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Project");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.RefreshToken", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Role", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Roles_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.RolePermission", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "Company")
                        .WithMany("RolePermissions")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_RolePermissions_Company");

                    b.HasOne("Fusion.Repository.Entities.FunctionInPage", "Function")
                        .WithMany("RolePermissions")
                        .HasForeignKey("FunctionId")
                        .HasConstraintName("FK_RolePermissions_Function");

                    b.HasOne("Fusion.Repository.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RolePermissions_Role");

                    b.Navigation("Company");

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Sprint", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Project", "Project")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Sprints_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TaskLogEvent", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "Actor")
                        .WithMany("TaskLogEvents")
                        .HasForeignKey("ActorId")
                        .HasConstraintName("FK_TaskLogEvent_Actor");

                    b.HasOne("Fusion.Repository.Entities.ProjectTask", "Task")
                        .WithMany("TaskLogEvents")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_TaskLogEvent_Task");

                    b.Navigation("Actor");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TaskWorkflow", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "AssignUser")
                        .WithMany("TaskWorkflows")
                        .HasForeignKey("AssignUserId")
                        .HasConstraintName("FK_TaskWorkflow_AssignUser");

                    b.HasOne("Fusion.Repository.Entities.ProjectTask", "Task")
                        .WithMany("TaskWorkflows")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_TaskWorkflow_Task");

                    b.HasOne("Fusion.Repository.Entities.WorkflowStatus", "WorkflowStatus")
                        .WithMany("TaskWorkflows")
                        .HasForeignKey("WorkflowStatusId")
                        .HasConstraintName("FK_TaskWorkflow_Status");

                    b.Navigation("AssignUser");

                    b.Navigation("Task");

                    b.Navigation("WorkflowStatus");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Ticket", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Tickets_Project");

                    b.HasOne("Fusion.Repository.Entities.WorkflowStatus", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Tickets_Status");

                    b.HasOne("Fusion.Repository.Entities.User", "SubmittedByNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("SubmittedBy")
                        .HasConstraintName("FK_Tickets_Submitter");

                    b.Navigation("Project");

                    b.Navigation("Status");

                    b.Navigation("SubmittedByNavigation");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TicketComment", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "AuthorUser")
                        .WithMany("TicketComments")
                        .HasForeignKey("AuthorUserId")
                        .HasConstraintName("FK_TicketComments_Author");

                    b.HasOne("Fusion.Repository.Entities.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK_TicketComments_Ticket");

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.TransactionPayment", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany("TransactionPayments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransactionPayments_SubscriptionPackage");

                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("TransactionPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransactionPayments_User");

                    b.Navigation("SubscriptionPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserDevice", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserRole", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.UserSubscription", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscriptions_SubscriptionPackage");

                    b.HasOne("Fusion.Repository.Entities.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscriptions_User");

                    b.Navigation("SubscriptionPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Workflow", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Company", "Company")
                        .WithMany("Workflows")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Workflows_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.WorkflowStatus", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.Workflow", "Workflow")
                        .WithMany("WorkflowStatuses")
                        .HasForeignKey("WorkflowId")
                        .HasConstraintName("FK_WorkflowStatus_Workflow");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("Fusion.Repository.Entities.WorkflowStatus", "FromStatus")
                        .WithMany("WorkflowTransitionFromStatuses")
                        .HasForeignKey("FromStatusId")
                        .HasConstraintName("FK_WorkflowTransitions_From");

                    b.HasOne("Fusion.Repository.Entities.WorkflowStatus", "ToStatus")
                        .WithMany("WorkflowTransitionToStatuses")
                        .HasForeignKey("ToStatusId")
                        .HasConstraintName("FK_WorkflowTransitions_To");

                    b.HasOne("Fusion.Repository.Entities.Workflow", "Workflow")
                        .WithMany("WorkflowTransitions")
                        .HasForeignKey("WorkflowId")
                        .HasConstraintName("FK_WorkflowTransitions_Workflow");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Company", b =>
                {
                    b.Navigation("CompanyFriendshipCompanyAs");

                    b.Navigation("CompanyFriendshipCompanyBs");

                    b.Navigation("CompanyMembers");

                    b.Navigation("ProjectCompanies");

                    b.Navigation("ProjectCompanyHireds");

                    b.Navigation("ProjectRequestExecutorCompanies");

                    b.Navigation("ProjectRequestRequesterCompanies");

                    b.Navigation("RolePermissions");

                    b.Navigation("Roles");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.FunctionInPage", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectTasks");

                    b.Navigation("Sprints");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectRequest", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.ProjectTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskLogEvents");

                    b.Navigation("TaskWorkflows");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Sprint", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.SubscriptionPackage", b =>
                {
                    b.Navigation("TransactionPayments");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Ticket", b =>
                {
                    b.Navigation("TicketComments");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Companies");

                    b.Navigation("CompanyFriendships");

                    b.Navigation("CompanyMembers");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectRequests");

                    b.Navigation("ProjectTasks");

                    b.Navigation("Projects");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TaskLogEvents");

                    b.Navigation("TaskWorkflows");

                    b.Navigation("TicketComments");

                    b.Navigation("Tickets");

                    b.Navigation("TransactionPayments");

                    b.Navigation("UserDevices");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.Workflow", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("WorkflowStatuses");

                    b.Navigation("WorkflowTransitions");
                });

            modelBuilder.Entity("Fusion.Repository.Entities.WorkflowStatus", b =>
                {
                    b.Navigation("TaskWorkflows");

                    b.Navigation("Tickets");

                    b.Navigation("WorkflowTransitionFromStatuses");

                    b.Navigation("WorkflowTransitionToStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
